<?php

return array (
  'version' => '5.7.3',
  'title' => 'Local Attractions',
  'type' => 'attractions',
  'id' => '630e5f201f2a2',
  'updated' => 1662666497,
  'columns' => 
  array (
    '5d1a9d13925fe' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '120',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '100',
      'image_size_h' => '100',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5d1a9d13925fe',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '630e69c48c49bc' => 
    array (
      'type' => 'field_630e670dfc8af',
      'label' => 'Phone',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '630e69c48c49bc',
    ),
    '5d1a9d13a4217' => 
    array (
      'type' => 'field_5d1a88d99f154',
      'label' => 'Address',
      'width' => '',
      'width_unit' => '%',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5d1a9d13a4217',
    ),
    '5d1a9d13a525d' => 
    array (
      'type' => 'field_5d1a88fb9f155',
      'label' => 'Custom URL',
      'width' => '',
      'width_unit' => '%',
      'link_label' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5d1a9d13a525d',
    ),
    '630e69b8f6c8b4' => 
    array (
      'type' => 'column-excerpt',
      'label' => 'Excerpt',
      'width' => '',
      'width_unit' => '%',
      'excerpt_length' => '20',
      'before' => '',
      'after' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '630e69b8f6c8b4',
    ),
    '5d1a9d7989da7' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Type',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'attractiontype',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'off',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5d1a9d7989da7',
    ),
    '631a46fd97ced8' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '',
      'width_unit' => '%',
      'use_icon' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '631a46fd97ced8',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'on',
    'hide_export' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);